image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r ./requirements.txt
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.6.5:M/0xh/MNGJTptXts7fD1Ug==
    - hbenl.vscode-test-explorer@2.19.5:yg+hg6b1O51L7NliE9pc5Q==