# Generated by Django 3.1.4 on 2021-01-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_3d', models.CharField(max_length=3)),
                ('code_2d', models.CharField(max_length=2, unique=True)),
                ('Name_fr', models.CharField(max_length=50, unique=True)),
                ('Name_eng', models.CharField(max_length=50, unique=True)),
                ('Continent', models.CharField(max_length=50)),
                ('Continent2', models.CharField(blank=True, max_length=50)),
                ('Translated', models.BooleanField(default=False)),
            ],
        ),
    ]
