# Generated by Django 3.1.4 on 2021-01-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='code_3d',
            new_name='flagcode',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='code_2d',
        ),
        migrations.AddField(
            model_name='countries',
            name='langcode',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
