# Generated by Django 3.1.4 on 2021-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20210122_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langcode', models.CharField(max_length=3, unique=True)),
                ('Name_fr', models.CharField(max_length=50, unique=True)),
                ('Name_eng', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='contrycode',
            new_name='countrycode',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='langcode',
        ),
        migrations.AddField(
            model_name='countries',
            name='spoken_languages',
            field=models.ManyToManyField(to='translation.Language'),
        ),
    ]
