# Generated by Django 3.1.5 on 2021-01-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_auto_20210122_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
