# Generated by Django 3.1.4 on 2021-02-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_auto_20210209_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['Name_fr']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['Name_fr']},
        ),
    ]
