# Generated by Django 3.1.4 on 2021-03-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0009_auto_20210210_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='Validated',
            field=models.BooleanField(default=False),
        ),
    ]
